### PR TITLE
got the IDs in the array. Addressing issue #1

### PR DESCRIPTION
**Pull request by mridulg**
Get a list of Pro names and convert it into an array. #1

### CODE REVIEW

**Comment by yongzhihuang** [comment]
Thank you SO much for such quick work!

I would merge your request. However I made a giant mistake of not checking the recency of that list, that page of the wiki was outdated :(

So Let me know if you would like to update the list to pull data from the following URLs instead 
http://lol.gamepedia.com/Active/LPL
http://lol.gamepedia.com/Active/NALCS
http://lol.gamepedia.com/Active/LCK

If not I will gladly open another issue.

Thanks again @mridulg

**Comment by mridulg** [comment]
okay @yongzhihuang 
So I basically scrape data from all these links and add them to a single array?

EDIT : done with parsing data from the links above

**Comment by yongzhihuang** [comment]
@mridulg That is correct. I see in the latest PR it now contains names from that first link, can you add the rest from the last 2 links as well?

http://lol.gamepedia.com/Active/NALCS
http://lol.gamepedia.com/Active/LCK

**Comment by mridulg** [comment]
@yongzhihuang I believe I got data from all the three links. There was a total of 236 entries combined, and 9 were duplicates (overlapping, I suppose).

**Comment by yongzhihuang** [comment]
@mridulg Yes you did indeed! Sorry. Thank you! Closing! and Enjoy Hacktoberfest.

**Pull request merged**
